---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: belimo-frontend
  labels:
    app: belimo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belimo-frontend
  template:
    metadata:
      labels:
        app: belimo-frontend
    spec:
      containers:
      - name: belimo-frontend
        image: robertbrem/belimo-frontend:todo
        env:
        - name: VERSION
          value: "todo"
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 3
        resources:
          limits:
            cpu: '0.5'
            memory: 512Mi
          requests:
            cpu: '0.25'
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: belimo-frontend
spec:
  selector:
    app: belimo-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31300
  type: NodePort
